DATALOADER:
  BATCH_SIZE: 64
  SHUFFLE: True
  NUM_WORKERS: 0
  DROP_LAST: True
  PIN_MEMORY: True

MODEL:
  PAD_TS:
    HIDDEN_SIZE: 128
    NUM_HEADS: 4
    N_ENCODER: 1
    N_DECODER: 3
    FEATURE_LAST: True
    MLP_RATIO: 4.0
    DROPOUT: 0.0

TRAIN:
  MICROBATCH: -1
  LOG_INTERVAL: 10
  SAVE_INTERVAL: 5e3
  MMD_ALPHA: 0.0008

OPTIM:
  LR: 1e-4
  WEIGHT_DECAY: 0.0
  LR_ANNEAL_STEPS: 70000

DIFFUSION:
  PREDICT_XSTART: True
  DIFFUSION_STEPS: 250
  NOISE_SCHEDULE: "cosine"
  LOSS: "MSE_MMD"
  RESCALE_TIMESTEPS: False
  SCHEDULE_SAMPLER: "batch"